snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/14.yaml

packages:
- .

extra-deps:
  - github: TheMarkersFoundation/markers
    commit: c3be7396804dbac0aae81332ab6553636595cae7
